/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-dm-sans)", "system-ui", "sans-serif"],
        display: ["var(--font-syne)", "system-ui", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "monospace"],
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        brand: {
          50: "#eef2ff", 100: "#e0e7ff", 200: "#c7d2fe", 300: "#a5b4fc",
          400: "#818cf8", 500: "#6366f1", 600: "#4f46e5", 700: "#4338ca",
          800: "#3730a3", 900: "#312e81",
        },
        gold: { DEFAULT: "#F5B942", light: "#FFD700", dark: "#C9900B" },
        success: "#34D399",
        danger: "#F87171",
        warning: "#FBBF24",
      },
      animation: {
        "fade-up": "fadeUp 0.6s ease both",
        "fade-in": "fadeIn 0.4s ease both",
        "float": "float 4s ease-in-out infinite",
        "pulse-glow": "pulseGlow 2.5s ease-in-out infinite",
        "shimmer": "shimmer 2s linear infinite",
        "spin-slow": "spin 8s linear infinite",
        "orb-float": "orbFloat 8s ease-in-out infinite",
        "gradient-shift": "gradientShift 6s ease infinite",
        "count-up": "countUp 0.8s ease both",
        "slide-up": "slideUpFade 0.5s ease both",
        "scale-in": "scaleIn 0.3s ease both",
        "border-pulse": "borderPulse 2s ease-in-out infinite",
      },
      keyframes: {
        fadeUp: { "0%": { opacity: "0", transform: "translateY(24px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        fadeIn: { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        float: { "0%,100%": { transform: "translateY(0px)" }, "50%": { transform: "translateY(-12px)" } },
        pulseGlow: { "0%,100%": { boxShadow: "0 0 20px rgba(99,102,241,0.2)" }, "50%": { boxShadow: "0 0 40px rgba(99,102,241,0.5)" } },
        shimmer: { "0%": { backgroundPosition: "-200% center" }, "100%": { backgroundPosition: "200% center" } },
        orbFloat: { "0%,100%": { transform: "translate(0,0) scale(1)" }, "33%": { transform: "translate(20px,-15px) scale(1.03)" }, "66%": { transform: "translate(-15px,8px) scale(0.97)" } },
        gradientShift: { "0%,100%": { backgroundPosition: "0% 50%" }, "50%": { backgroundPosition: "100% 50%" } },
        countUp: { "0%": { opacity: "0", transform: "scale(0.8)" }, "100%": { opacity: "1", transform: "scale(1)" } },
        slideUpFade: { "0%": { opacity: "0", transform: "translateY(16px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        scaleIn: { "0%": { opacity: "0", transform: "scale(0.9)" }, "100%": { opacity: "1", transform: "scale(1)" } },
        borderPulse: { "0%,100%": { borderColor: "rgba(99,102,241,0.2)" }, "50%": { borderColor: "rgba(99,102,241,0.6)" } },
      },
      boxShadow: {
        "glow-sm": "0 0 12px rgba(99,102,241,0.2)",
        "glow": "0 0 24px rgba(99,102,241,0.3)",
        "glow-lg": "0 0 48px rgba(99,102,241,0.4)",
        "glow-gold": "0 0 24px rgba(245,185,66,0.3)",
        "card": "0 4px 24px rgba(0,0,0,0.4), 0 1px 0 rgba(255,255,255,0.04) inset",
        "card-hover": "0 8px 48px rgba(0,0,0,0.5), 0 1px 0 rgba(255,255,255,0.06) inset",
        "premium": "0 20px 60px rgba(0,0,0,0.6), 0 0 0 1px rgba(99,102,241,0.1)",
      },
      borderRadius: { "4xl": "2rem", "5xl": "2.5rem" },
    },
  },
  plugins: [],
};
